name: inductor-perf-nightly

on:
  schedule:
    - cron: 0 7 * * 1-6
    - cron: 0 7 * * 0
  workflow_dispatch:
    inputs:
      training:
        description: Run training?
        required: false
        type: boolean
        default: true
      inference:
        description: Run inference?
        required: false
        type: boolean
        default: false
      default:
        description: Run inductor_default?
        required: false
        type: boolean
        default: true
      dynamic:
        description: Run inductor_dynamic_shapes?
        required: false
        type: boolean
        default: true
      cudagraphs:
        description: Run inductor_cudagraphs?
        required: false
        type: boolean
        default: true
      cppwrapper:
        description: Run inductor_cpp_wrapper for inference?
        required: false
        type: boolean
        default: false
      freezing_cudagraphs:
        description: Run inductor_cudagraphs with freezing for inference?
        required: false
        type: boolean
        default: false
      aotinductor:
        description: Run aot_inductor for inference?
        required: false
        type: boolean
        default: false
      maxautotune:
        description: Run inductor_max_autotune?
        required: false
        type: boolean
        default: false
      nvidia_a100:
        description: Run test on Nvidia A100 GPU?
        required: false
        type: boolean
        default: true
      nvidia_t4:
        description: Run test on Nvidia T4 GPU?
        required: false
        type: boolean
        default: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ github.ref_type == 'branch' && github.sha }}-${{ github.event_name == 'workflow_dispatch' }}-${{ github.event_name == 'schedule' }}
  cancel-in-progress: true

jobs:
  inductor-perf-test-on-a100-nvidia-gpu:
    name: inductor-perf-test-on-a100-nvidia-gpu
    uses: ./.github/workflows/inductor-a100-perf-test.yml
    if: ${{ inputs.nvidia_a100 == true }}
    with:
      training: ${{ inputs.training }}
      inference: ${{ inputs.inference }}
      default: ${{ inputs.default }}
      dynamic: ${{ inputs.dynamic }}
      cudagraphs: ${{ inputs.cudagraphs }}
      cppwrapper: ${{ inputs.cppwrapper }}
      freezing_cudagraphs: ${{ inputs.freezing_cudagraphs }}
      aotinductor: ${{ inputs.aotinductor }}
      maxautotune: ${{ inputs.maxautotune }}

  inductor-perf-test-on-t4-nvidia-gpu:
    name: inductor-perf-test-on-t4-nvidia-gpu
    uses: ./.github/workflows/inductor-t4-perf-test.yml
    if: ${{ inputs.nvidia_t4 == true }}
    with:
      training: ${{ inputs.training }}
      inference: ${{ inputs.inference }}
      default: ${{ inputs.default }}
      dynamic: ${{ inputs.dynamic }}
      cudagraphs: ${{ inputs.cudagraphs }}
      cppwrapper: ${{ inputs.cppwrapper }}
      freezing_cudagraphs: ${{ inputs.freezing_cudagraphs }}
      aotinductor: ${{ inputs.aotinductor }}
      maxautotune: ${{ inputs.maxautotune }}


