name: inductor-T4-perf-nightly

on:
  workflow_call:
    inputs:
      training:
        description: Run training?
        required: false
        type: boolean
        default: false
      inference:
        description: Run inference?
        required: false
        type: boolean
        default: true
      default:
        description: Run inductor_default?
        required: false
        type: boolean
        default: true
      dynamic:
        description: Run inductor_dynamic_shapes?
        required: false
        type: boolean
        default: true
      cudagraphs:
        description: Run inductor_cudagraphs?
        required: false
        type: boolean
        default: true
      cppwrapper:
        description: Run inductor_cpp_wrapper for inference?
        required: false
        type: boolean
        default: false
      freezing_cudagraphs:
        description: Run inductor_cudagraphs with freezing for inference?
        required: false
        type: boolean
        default: false
      aotinductor:
        description: Run aot_inductor for inference?
        required: false
        type: boolean
        default: false
      maxautotune:
        description: Run inductor_max_autotune?
        required: false
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ github.ref_type == 'branch' && github.sha }}-${{ github.event_name == 'workflow_dispatch' }}-${{ github.event_name == 'schedule' }}-t4
  cancel-in-progress: true

jobs:
  linux-focal-cuda12_1-py3_10-gcc9-inductor-build:
    name: cuda12.1-py3.10-gcc9-sm75
    uses: ./.github/workflows/_linux-build.yml
    with:
      build-environment: linux-focal-cuda12.1-py3.10-gcc9-sm75
      docker-image-name: pytorch-linux-focal-cuda12.1-cudnn8-py3-gcc9-inductor-benchmarks
      cuda-arch-list: '7.5'
      test-matrix: |
        { include: [
          { config: "inductor_huggingface_perf", shard: 1, num_shards: 3, runner: "linux.g4dn.4xlarge" },
          { config: "inductor_huggingface_perf", shard: 2, num_shards: 3, runner: "linux.g4dn.4xlarge" },
          { config: "inductor_huggingface_perf", shard: 3, num_shards: 3, runner: "linux.g4dn.4xlarge" },
          { config: "inductor_timm_perf", shard: 1, num_shards: 5, runner: "linux.g4dn.4xlarge" },
          { config: "inductor_timm_perf", shard: 2, num_shards: 5, runner: "linux.g4dn.4xlarge" },
          { config: "inductor_timm_perf", shard: 3, num_shards: 5, runner: "linux.g4dn.4xlarge" },
          { config: "inductor_timm_perf", shard: 4, num_shards: 5, runner: "linux.g4dn.4xlarge" },
          { config: "inductor_timm_perf", shard: 5, num_shards: 5, runner: "linux.g4dn.4xlarge" },
          { config: "inductor_torchbench_perf", shard: 1, num_shards: 4, runner: "linux.g4dn.4xlarge" },
          { config: "inductor_torchbench_perf", shard: 2, num_shards: 4, runner: "linux.g4dn.4xlarge" },
          { config: "inductor_torchbench_perf", shard: 3, num_shards: 4, runner: "linux.g4dn.4xlarge" },
          { config: "inductor_torchbench_perf", shard: 4, num_shards: 4, runner: "linux.g4dn.4xlarge" },
        ]}
    secrets:
      HUGGING_FACE_HUB_TOKEN: ${{ secrets.HUGGING_FACE_HUB_TOKEN }}

  linux-focal-cuda12_1-py3_10-gcc9-inductor-test-nightly:
    name: cuda12.1-py3.10-gcc9-sm75
    uses: ./.github/workflows/_linux-test.yml
    needs: linux-focal-cuda12_1-py3_10-gcc9-inductor-build
    if: github.event.schedule == '0 7 * * 1-6'
    with:
      build-environment: linux-focal-cuda12.1-py3.10-gcc9-sm75
      dashboard-tag: inference-true-default-true-dynamic-true-cudagraphs-true-aotinductor-true-freezing_cudagraphs-true
      docker-image: ${{ needs.linux-focal-cuda12_1-py3_10-gcc9-inductor-build.outputs.docker-image }}
      test-matrix: ${{ needs.linux-focal-cuda12_1-py3_10-gcc9-inductor-build.outputs.test-matrix }}
      use-gha: anything-non-empty-to-use-gha
      timeout-minutes: 720
    secrets:
      HUGGING_FACE_HUB_TOKEN: ${{ secrets.HUGGING_FACE_HUB_TOKEN }}

  linux-focal-cuda12_1-py3_10-gcc9-inductor-test-weekly:
    name: cuda12.1-py3.10-gcc9-sm75
    uses: ./.github/workflows/_linux-test.yml
    needs: linux-focal-cuda12_1-py3_10-gcc9-inductor-build
    if: github.event.schedule == '0 7 * * 0'
    with:
      build-environment: linux-focal-cuda12.1-py3.10-gcc9-sm75
      dashboard-tag: inference-true-default-true-dynamic-true-cudagraphs-true-aotinductor-true-freezing_cudagraphs-true-maxautotune-true
      docker-image: ${{ needs.linux-focal-cuda12_1-py3_10-gcc9-inductor-build.outputs.docker-image }}
      test-matrix: ${{ needs.linux-focal-cuda12_1-py3_10-gcc9-inductor-build.outputs.test-matrix }}
      use-gha: anything-non-empty-to-use-gha
      timeout-minutes: 1440
    secrets:
      HUGGING_FACE_HUB_TOKEN: ${{ secrets.HUGGING_FACE_HUB_TOKEN }}

  linux-focal-cuda12_1-py3_10-gcc9-inductor-test:
    name: cuda12.1-py3.10-gcc9-sm75
    uses: ./.github/workflows/_linux-test.yml
    needs: linux-focal-cuda12_1-py3_10-gcc9-inductor-build
    if: github.event_name == 'workflow_dispatch'
    with:
      build-environment: linux-focal-cuda12.1-py3.10-gcc9-sm75
      dashboard-tag: training-${{ inputs.training }}-inference-${{ inputs.inference }}-default-${{ inputs.default }}-dynamic-${{ inputs.dynamic }}-cudagraphs-${{ inputs.cudagraphs }}-cppwrapper-${{ inputs.cppwrapper }}-aotinductor-${{ inputs.aotinductor }}-maxautotune-${{ inputs.maxautotune }}-freezing_cudagraphs-${{ inputs.freezing_cudagraphs }}
      docker-image: ${{ needs.linux-focal-cuda12_1-py3_10-gcc9-inductor-build.outputs.docker-image }}
      test-matrix: ${{ needs.linux-focal-cuda12_1-py3_10-gcc9-inductor-build.outputs.test-matrix }}
      use-gha: anything-non-empty-to-use-gha
      timeout-minutes: 720
    secrets:
      HUGGING_FACE_HUB_TOKEN: ${{ secrets.HUGGING_FACE_HUB_TOKEN }}
