name: Validate and check if PR is mergable

on:
  pull_request:

jobs:
  do_merge_dry_run:
    name: mergability_check_${{ github.event.pull_request.number }}
    runs-on: linux.20_04.4x
    env:
        GH_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
    steps:
      - name: Checkout repo
        id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          check-latest: false
          cache: pip
          architecture: x64
      - run: pip install pyyaml==6.0 rockset==1.0.3

      - name: Dry Run Merge PR
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUM: ${{ github.event.pull_request.number  }}
          ROCKSET_API_KEY: ${{ secrets.ROCKSET_API_KEY }}
        run: |
          set -ex
          trap 'if [ $? -ne 0 ]; then echo "This PR is not mergable, please rebase and fix merge conflicts"; fi' EXIT
          python3 .github/scripts/trymerge.py --force --dry-run "${PR_NUM}"
# We want newer merge commands to supercede old ones
concurrency:
  group: mergability-check-${{ github.event.pull_request.number  }}
  cancel-in-progress: true
